server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://192.168.0.28:3306/document_management_system
    username: DIGIGRN
    password: DIGIGRN

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


app:
  url:
    verify-email: http://192.168.0.111:8081/public/verify-email?token=
