server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://192.168.0.61:3306/document_management_system_py
    username: DMSTEST
    password: DmsTEST8888$#@!

  jpa:
    hibernate:
      ddl-auto: validate